FROM python:3.8-slim
WORKDIR /app
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt
COPY config.json /app/
COPY config.py /app/
COPY github_issues_main.py /app/
COPY test_github_issues_main.py /app/
CMD [ "python", "github_issues_main.py" ]